//
// Generated file, do not edit! Created by opp_msgtool 6.0 from messages/client_arrived/client_arrived.msg.
//

#ifndef __CLIENT_ARRIVED_M_H
#define __CLIENT_ARRIVED_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class client_arrived_m;
/**
 * Class generated from <tt>messages/client_arrived/client_arrived.msg:15</tt> by opp_msgtool.
 * <pre>
 * //
 * // This program is free software: you can redistribute it and/or modify
 * // it under the terms of the GNU Lesser General Public License as published by
 * // the Free Software Foundation, either version 3 of the License, or
 * // (at your option) any later version.
 * // 
 * // This program is distributed in the hope that it will be useful,
 * // but WITHOUT ANY WARRANTY; without even the implied warranty of
 * // MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * // GNU Lesser General Public License for more details.
 * // 
 * // You should have received a copy of the GNU Lesser General Public License
 * // along with this program.  If not, see http://www.gnu.org/licenses/.
 * //
 * message client_arrived_m
 * {
 *     unsigned long user_id;
 * }
 * </pre>
 */
class client_arrived_m : public ::omnetpp::cMessage
{
  protected:
    unsigned long user_id = 0;

  private:
    void copy(const client_arrived_m& other);

  protected:
    bool operator==(const client_arrived_m&) = delete;

  public:
    client_arrived_m(const char *name=nullptr, short kind=0);
    client_arrived_m(const client_arrived_m& other);
    virtual ~client_arrived_m();
    client_arrived_m& operator=(const client_arrived_m& other);
    virtual client_arrived_m *dup() const override {return new client_arrived_m(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual unsigned long getUser_id() const;
    virtual void setUser_id(unsigned long user_id);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const client_arrived_m& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, client_arrived_m& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline client_arrived_m *fromAnyPtr(any_ptr ptr) { return check_and_cast<client_arrived_m*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __CLIENT_ARRIVED_M_H

